### ISSUE TITLE
Compiler Errors with NPE

### ISSUE THREAD

**Issue by XmiliaH** [xtclang/xvm#111]
**Describe the bug**
When trying to compile `console.print(switch(""){ default: "Hello World"; });` the compiler encounters a NullPointerException.
```
java.lang.NullPointerException: Cannot read the array length because "cases" is null
        at org.xvm.asm.ast.SwitchAST.<init>(SwitchAST.java:83)
        at org.xvm.compiler.ast.SwitchExpression.getExprAST(SwitchExpression.java:386)
        at org.xvm.compiler.ast.InvocationExpression.generateAssignments(InvocationExpression.java:1503)
        at org.xvm.compiler.ast.ExpressionStatement.emit(ExpressionStatement.java:110)
        at org.xvm.compiler.ast.Statement.completes(Statement.java:229)
        at org.xvm.compiler.ast.StatementBlock.emit(StatementBlock.java:561)
        at org.xvm.compiler.ast.Statement.completes(Statement.java:229)
        at org.xvm.compiler.ast.StatementBlock.compileMethod(StatementBlock.java:362)
        at org.xvm.compiler.ast.StatementBlock.compileMethod(StatementBlock.java:337)
        at org.xvm.compiler.ast.MethodDeclarationStatement.compileBody(MethodDeclarationStatement.java:1062)
        at org.xvm.compiler.ast.MethodDeclarationStatement.generateCode(MethodDeclarationStatement.java:1057)
        at org.xvm.compiler.ast.StageMgr.processInternal(StageMgr.java:226)
        at org.xvm.compiler.ast.StageMgr.processChildrenExcept(StageMgr.java:372)
        at org.xvm.compiler.ast.StageMgr.processChildren(StageMgr.java:342)
        at org.xvm.compiler.ast.StageMgr.processInternal(StageMgr.java:235)
        at org.xvm.compiler.ast.StageMgr.processChildrenExcept(StageMgr.java:372)
        at org.xvm.compiler.ast.StageMgr.processChildren(StageMgr.java:342)
        at org.xvm.compiler.ast.TypeCompositionStatement.generateCode(TypeCompositionStatement.java:2626)
```

**To Reproduce**
1. Edit TestSimple.x to include `console.print(switch(""){ default: "Hello World"; });`.
2. Build with `gradlew runOne`

**Expected behavior**
Successful compile and output of `Hello World` when run.

**Comment by ggleyzer** [comment]
Fixed by the commit: [Fix a compiler assertion (Issue 111)](https://github.com/xtclang/xvm/commit/2a821d508865b0ba0f9ec7f358b30e19f5994c01)
