### ISSUE TITLE
Compiler crash with NPE

### ISSUE THREAD

**Issue by XmiliaH** [xtclang/xvm#255]
**Describe the bug**
Compiler crashes with NPE when trying to compile:

```java
module TestCustom {
    @Inject ecstasy.io.Console console;

    void run() {
        interface I {
            String giveMessage();
        }
        interface I {
            String giveMessage();
        }
        class B {
            String giveMessage() { return "Message"; }
        }
        console.print($"As I: {new B().as(I).giveMessage()}");
    }
}
```
with the following stack trace.
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.xvm.asm.Component.isMethodContainer()" because "container" is null
        at org.xvm.compiler.ast.MethodDeclarationStatement.resolveNames(MethodDeclarationStatement.java:525)
        at org.xvm.compiler.ast.StageMgr.processInternal(StageMgr.java:218)
        at org.xvm.compiler.ast.StageMgr.processChildrenExcept(StageMgr.java:372)
        at org.xvm.compiler.ast.StageMgr.processChildren(StageMgr.java:342)
        at org.xvm.compiler.ast.StageMgr.processInternal(StageMgr.java:235)
        at org.xvm.compiler.ast.StageMgr.processChildrenExcept(StageMgr.java:372)
        at org.xvm.compiler.ast.StageMgr.processChildren(StageMgr.java:342)
        at org.xvm.compiler.ast.StageMgr.processInternal(StageMgr.java:235)
        at org.xvm.compiler.ast.StageMgr.processChildrenExcept(StageMgr.java:372)
        at org.xvm.compiler.ast.StageMgr.processChildren(StageMgr.java:342)
        at org.xvm.compiler.ast.StageMgr.processInternal(StageMgr.java:235)
        at org.xvm.compiler.ast.StageMgr.processComplete(StageMgr.java:91)
        at org.xvm.compiler.ast.AstNode.catchUpChildren(AstNode.java:867)
        at org.xvm.compiler.ast.MethodDeclarationStatement.validateContent(MethodDeclarationStatement.java:676)
        at org.xvm.compiler.ast.StageMgr.processInternal(StageMgr.java:222)
        at org.xvm.compiler.ast.StageMgr.processChildrenExcept(StageMgr.java:372)
        at org.xvm.compiler.ast.StageMgr.processChildren(StageMgr.java:342)
        at org.xvm.compiler.ast.StageMgr.processInternal(StageMgr.java:235)
        at org.xvm.compiler.ast.StageMgr.processChildrenExcept(StageMgr.java:372)
        at org.xvm.compiler.ast.StageMgr.processChildren(StageMgr.java:342)
        at org.xvm.compiler.ast.TypeCompositionStatement.validateContent(TypeCompositionStatement.java:2337)
        at org.xvm.compiler.ast.StageMgr.processInternal(StageMgr.java:222)
        at org.xvm.compiler.ast.StageMgr.processComplete(StageMgr.java:91)
        at org.xvm.compiler.Compiler.validateExpressions(Compiler.java:277)
        at org.xvm.tool.Compiler.validateExpressions(Compiler.java:507)
        at org.xvm.tool.Compiler.process(Compiler.java:317)
        at org.xvm.tool.Launcher.run(Launcher.java:148)
        at org.xvm.tool.Runner.process(Runner.java:265)
        at org.xvm.tool.Launcher.run(Launcher.java:148)
        at org.xvm.tool.Runner.launch(Runner.java:70)
        at org.xvm.tool.Runner.main(Runner.java:61)
        at org.xvm.tool.Launcher.main(Launcher.java:100)
```

**To Reproduce**
1. Create a `manualTests/src/main/x/test.x` file with the above code.
2. Run `xec -L build/xtc/main/lib -o build/xtc/main/lib src/main/x/test.x` in the `manualTests` directory.

**Expected behavior**
No crash, but maybe a compiler diagnostic.

**Comment by ggleyzer** [comment]
Thank you! Will fix

**Comment by ggleyzer** [comment]
Fixed by [this commit](https://github.com/xtclang/xvm/commit/55b48b2592f080dd4b7555621125f9bf823494fb)

Thanks again!
